_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  common: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datastore: 0
  datetime: 0
  dblog: 0
  dkan: 0
  dkan_js_frontend: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  harvest: 0
  help: 0
  history: 0
  image: 0
  json_form_widget: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  metastore: 0
  metastore_admin: 0
  metastore_search: 0
  moderated_content_bulk_publish: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  search_api: 0
  search_api_db: 0
  select2: 0
  select_or_other: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  workflows: 0
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
profile: standard
