_core:
  default_config_hash: 4PFQbB8CBi-UlhLcG5XDaw58nmLFgZYh1hWXUMdoAhI
css_folder: /frontend/build/static/css/
js_folder: /frontend/build/static/js/
routes:
  - 'home,/home'
  - 'about,/about'
  - 'api,/api'
  - 'dataset,/dataset/{id}'
  - 'datasetapi,/dataset/{id}/api'
  - 'search,/search'
  - 'publishers,/publishers'
