_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 2ac50eaa-7bf1-412c-bdb0-7ece8bf3a19e
name: 'Dkan CI'
mail: patelnir@paho.org
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
